project:
  type: website
  output-dir: 'docs'

website:
  title: "GBBC Sunday School"
  navbar:
    logo: 'docs/profile.png'
    right:
      - about.qmd
      - icon: facebook
        text: Facebook
        href: https://www.facebook.com/GBBCVillagers
format:
  html:
    smooth-scroll: true
    link-external-newwindow: true
    theme: cosmo
    css: styles.css

editor: visual

